### PR TITLE
Add method to create a Stripe token from card parameters

### PR DESCRIPTION
**Pull request by tobycox**
Thanks for creating this! I'm using the Apple pay part of it, but we also allow users to input their credit card in to our own form, so I needed a way to easily create charges.

This PR exposes `createTokenWithCard` on the Stripe framework so that charges can be created manually.

### CODE REVIEW

**Comment by lrettig** [comment]
Great idea! I'll take a look today

**Comment by lrettig** [comment]
Hi Toby

Thanks again for submitting this, I think it's a great idea.

I ran into one issue testing it. I'm getting the following exception:

```
2016-01-27 16:02:17.293 example[86176:21534010] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb000000000008333
2016-01-27 16:02:17.294 [error][tid:main] Exception '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xb000000000008333' was thrown while invoking createTokenWithCard on target StripeNativeManager with params (
        {
        cvc = 123;
        expMonth = 12;
        expYear = 2099;
        number = 4242424242424242;
    },
    2,
    3
)
```

when I pass in this data:

```
    var params = {
      number:   4242424242424242,
      cvc:      123,
      expMonth: 12,
      expYear:  2099,
    };
```

It looks like the iOS code is expecting strings for all of the params, and crashes if you pass in numbers. It should be pretty easy to fix this--I'd probably wrap `createTokenWithCard` in JS, the way I've done for `paymentRequestWithApplePay`, to convert non-strings into strings. Let me know if you need a hand.

Cheers

Lane

**Comment by tobycox** [comment]
Good spot. I was already doing some munging of the data in Objective-C to get the types correct for the SPCardParams object, so I just added a little more inthere.

**Comment by lrettig** [comment]
Hi Toby

Sorry for the dumb question, but, if you're just trying to convert card details into a Stripe token, what's the advantage to doing it in native vs. using the Stripe JS SDK?

Thanks

**Comment by tobycox** [comment]
Totally not a dumb question. I could do that, but I wanted to use your library for the Apple Pay part of things, and it seemed overkill to separately include the Stripe JS library in order to handle straight credit cards when the functionality is already there, just not exposed.

**Comment by tobycox** [comment]
What's your thoughts on this @lrettig? Are you thinking it's not core to the library?

**Comment by lrettig** [comment]
Yes, sorry, just been distracted. I'll merge this in ASAP! Thanks for the
reminder.

**Comment by tobycox** [comment]
No worries! I rebased it so it's mergable.

**Comment by lrettig** [comment]
Thanks, finally got around to this. It's in master now, and I'll do another release once I've finished testing.

**Pull request merged**
