### PR TITLE
setRequiredBillingAddressFields configurable as option

### PR DESCRIPTION
**Pull request by richardgill**
We needed to disable billingAddress. 

This change mirrors how shippingAddress works.

### CODE REVIEW

**Comment by lrettig** [comment]
Hi @richardgill thanks for the PR! Do we need to add anything on the JS side for this?

**Comment by richardgill** [comment]
Everything seemed to work for me :).

**Comment by richardgill** [comment]
Can we merge, have been using for ages now. Seems fine.

**Comment by lrettig** [comment]
done, thanks, will release

**Pull request merged**
